title: Alhaad Gokhale
description: >- # this means to ignore newlines until "baseurl:"
  Personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alhaad.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

author: null
email: null

# Social media in footer.
twitter_username: alhaadgokhale
github_username:  alhaad
linkedin_username: alhaad-gokhale-0404ab84

# Enable Google Analytics
google_analytics: UA-71823202-1

# Enabling comments (via disqus)
disqus:
  shortname: alhaad

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
