title: Alhaad Gokhale
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alhaad.github.io/"
description: Personal website

# Social media in footer.
github_username:  alhaad
linkedin_username: alhaad-gokhale-0404ab84

webmaster_verifications:
  google: R2xG61UNUMFgK1oU5BXboz-fj2B4bjoNtYeFNBkSTzM

google_analytics: UA-71823202-1
disqus:
  shortname: alhaad

visited_countries: [India, United States, Sri Lanka, Singapore, Malaysia, Switzerland, Mexico, France, Italy, Spain, Iceland, Austria, Germany, Czech Republic, Israel, United Kingdom, Turkey]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
